### ISSUE TITLE
`pytest-xdist` not succeeding with python 3.6

### ISSUE THREAD

**Issue by kangwonlee** [kangwonlee/momisp#29]
* `enum34` in https://github.com/pytest-dev/pytest-xdist/issues/127 seems not included but still fails

```
Traceback (most recent call last):
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 3.2.1 (~/miniconda/envs/test-environment/lib/python3.6/site-packages), Requirement.parse('pytest>=3.6.0'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "~/miniconda/envs/test-environment/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/config.py", line 168, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/config.py", line 957, in pytest_cmdline_parse
    self.parse(args)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/config.py", line 1121, in parse
    self._preparse(args, addopts=addopts)
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/config.py", line 1084, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "~/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 515, in load_setuptools_entrypoints
    "Plugin %r could not be loaded: %s!" % (ep.name, e))
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'xdist' could not be loaded: (pytest 3.2.1 (~/miniconda/envs/test-environment/lib/python3.6/site-packages), Requirement.parse('pytest>=3.6.0'))!
```

* `conda list` as follows

```
$ conda list
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/travis/miniconda/envs/test-environment:
#
# Name                    Version                   Build  Channel
apipkg                    1.5                      py36_0  
attrs                     19.1.0                   py36_1  
backcall                  0.1.0                    py36_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py36_0  
ca-certificates           2019.1.23                     0  
certifi                   2019.3.9                 py36_0  
cycler                    0.10.0                   py36_0  
dbus                      1.13.2               hc3f9b76_0  
decorator                 4.4.0                    py36_1  
defusedxml                0.5.0                    py36_1  
entrypoints               0.3                      py36_0  
execnet                   1.5.0                    py36_0  
expat                     2.2.6                he6710b0_0  
fastcache                 1.0.2            py36h14c3975_2  
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8                  hab7d2ae_1  
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36h10f8cd9_2  
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
icu                       58.2                 h9c2bf20_1  
intel-openmp              2019.3                      199  
ipykernel                 5.1.0            py36h39e3cac_0  
ipython                   7.4.0            py36h39e3cac_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                7.4.2                    py36_0  
jedi                      0.13.3                   py36_0  
jinja2                    2.10                     py36_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.0.1                    py36_0  
jupyter                   1.0.0                    py36_7  
jupyter_client            5.2.4                    py36_0  
jupyter_console           6.0.0                    py36_0  
jupyter_core              4.4.0                    py36_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.36               hbc83047_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                he19cac6_0  
markupsafe                1.1.1            py36h7b6447c_0  
matplotlib                2.1.0            py36hba5de38_0  
mistune                   0.8.4            py36h7b6447c_0  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py36h7dd41cf_0  
mkl_random                1.0.1            py36h4414c95_1  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.1                hdf1c602_3  
mpmath                    1.1.0                    py36_0  
nbconvert                 5.4.1                    py36_3  
nbformat                  4.4.0                    py36_0  
ncurses                   6.1                  he6710b0_1  
notebook                  5.7.8                    py36_0  
numpy                     1.13.3           py36hdbf6ddf_4  
openssl                   1.0.2r               h7b6447c_0  
pandas                    0.23.4           py36h04863e7_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py36_1  
parso                     0.3.4                    py36_0  
patsy                     0.5.1                    py36_0  
pcre                      8.43                 he6710b0_0  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pip                       19.0.3                   py36_0  
prometheus_client         0.6.0                    py36_0  
prompt_toolkit            2.0.9                    py36_0  
ptyprocess                0.6.0                    py36_0  
py                        1.8.0                    py36_0  
pygments                  2.3.1                    py36_0  
pyparsing                 2.3.1                    py36_0  
pyqt                      5.6.0            py36h22d08a2_6  
pyrsistent                0.14.11          py36h7b6447c_0  
pytest                    3.2.1            py36h11ad3bb_1  
pytest-forked             1.0.2                    py36_0  
pytest-xdist              1.26.1                   py36_0  
python                    3.6.6                h6e4f718_2  
python-dateutil           2.8.0                    py36_0  
pytz                      2018.9                   py36_0  
pyzmq                     18.0.0           py36he6710b0_0  
qt                        5.6.2               hd25b39d_14  
qtconsole                 4.4.3                    py36_0  
readline                  7.0                  h7b6447c_5  
scipy                     0.19.1           py36h9976243_3  
send2trash                1.5.0                    py36_0  
setuptools                40.8.0                   py36_0  
sip                       4.18.1           py36hf484d3e_2  
six                       1.12.0                   py36_0  
sqlite                    3.27.2               h7b6447c_0  
statsmodels               0.9.0            py36h035aef0_0  
sympy                     1.1.1                    py36_0  
terminado                 0.8.1                    py36_1  
testpath                  0.4.2                    py36_0  
tk                        8.6.8                hbc83047_0  
tornado                   6.0.2            py36h7b6447c_0  
traitlets                 4.3.2                    py36_0  
wcwidth                   0.1.7                    py36_0  
webencodings              0.5.1                    py36_1  
wheel                     0.33.1                   py36_0  
widgetsnbextension        3.4.2                    py36_0  
xz                        5.2.4                h14c3975_4  
zeromq                    4.3.1                he6710b0_3  
zlib                      1.2.11               h7b6447c_3  
```

**Comment by kangwonlee** [comment]
* Available `pytest-xdist` versions

```pytest-xdist 1.17.1 py36_0
pytest-xdist 1.20.1 py36h25492f5_0
pytest-xdist 1.22.1 py36_0
pytest-xdist 1.22.2 py36_0
pytest-xdist 1.22.5 py36_0
pytest-xdist 1.22.5 py36h28b3542_0
pytest-xdist 1.23.0 py36h28b3542_0
pytest-xdist 1.23.2 py36_0
pytest-xdist 1.24.0 py36_0
pytest-xdist 1.24.1 py36_0
pytest-xdist 1.25.0 py36_0
pytest-xdist 1.26.0 py36_0
pytest-xdist 1.26.1 py36_0
```

**Comment by kangwonlee** [comment]
* Attempted a test : https://travis-ci.org/kangwonlee/test-pytest-xdist-py36

| version | result |
|:------:|:-------:|
| 1.17.1 | :smile: |
| 1.20.1 | :smile: |
| 1.22.1 | :smile: |
| 1.22.2 | :smile: |
| 1.22.5 | :smile: |
| 1.23.0 | :smile: |
| 1.23.2 | :smile: |
| 1.24.0 | :smile: |
| 1.24.1 | :smile: |
| 1.25.0 | ::sweat:: |
| 1.26.0 | ::sweat:: |
| 1.26.1 | ::sweat:: |

**Comment by kangwonlee** [comment]
* 80a85a6a33fc5a73b3706d6a109002d7ba47e940 resolves the issue
